import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased pt-16 dark:bg-[#0C0A09]`}>
        <Providers>
          <ClientOnlyHeaderAndCartModal />
          {children}
        </Providers>
      </body>
    </html>
  );
}

// Client-only wrapper for Header and CartModal
function ClientOnlyHeaderAndCartModal() {
  "use client";
  const { Header } = require("@/components/ui/header");
  const CartModal = require("./cart-modal").default;
  return (
    <>
      <Header />
      <CartModal />
    </>
  );
}
